<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SeedCommand</RootNamespace>
    <AssemblyName>SeedCommand</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <NoWarn>$(NoWarn);CS0618;CS0619</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.305" />
    <PackageReference Include="MySqlConnector" Version="2.3.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MenuManagerApi">
      <HintPath>M:\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\addons\counterstrikesharp\shared\MenuManagerApi\MenuManagerApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
