// SeedCommand for CS2 — WeaponPaints companion plugin.
//
// Code 100% generated by Claude Code (claude.ai/code).
//
// Commissioned by Mavi — https://steamcommunity.com/profiles/76561198147748231/
// Attribution to that Steam profile is required when redistributing this plugin.
// No monetary compensation requested — only attribution.
//
// Built on top of:
//   - WeaponPaints by Nereziel (https://github.com/Nereziel/cs2-WeaponPaints)
//   - CounterStrikeSharp framework (https://github.com/roflmuffin/CounterStrikeSharp)
//   - MenuManager by Schwarper (https://github.com/schwarper/cs2-MenuManager)
// All credit for the underlying skin/charm/sticker system goes to those projects.

using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Core.Attributes.Registration;
using CounterStrikeSharp.API.Core.Capabilities;
using CounterStrikeSharp.API.Modules.Commands;
using MenuManager;
using MySqlConnector;
using System.Globalization;
using System.Text.Json;

namespace SeedCommand;

// v4.0 — fully featured companion plugin:
//   !k        instant knife type -> skin chain with auto best seed + FN wear + visual refresh
//   !ws       instant skin menu for held weapon with auto best seed + FN wear + visual refresh
//   !gloves   instant gloves menu (all glove types/skins in one list)
//   !seed N   manually override paint seed on held weapon
//   !bestseed apply the best-known seed for the held weapon's current paint
//   !wear F   set wear/float of held weapon to F (e.g. !wear 0.001 = FN, !wear 0.5 = Battle-Scarred)
//   !fn       shorthand for !wear 0.000001
//
// DB triggers in best_seeds_setup.sql automatically apply the best seed + FN wear
// when any wp_player_skins row's paint_id changes.

public class SeedCommandPlugin : BasePlugin, IPluginConfig<SeedCommandConfig>
{
    public override string ModuleName    => "SeedCommand";
    public override string ModuleVersion => "4.6.0";
    public override string ModuleAuthor  => "Claude Code — commissioned by Mavi (steamcommunity.com/profiles/76561198147748231)";
    public override string ModuleDescription => "WeaponPaints companion: instant skin menus + best-seed + wear control";

    public SeedCommandConfig Config { get; set; } = new();
    public void OnConfigParsed(SeedCommandConfig cfg) { Config = cfg; }

    private string ConnString => $"Server={Config.DatabaseHost};Port={Config.DatabasePort};" +
                                  $"Database={Config.DatabaseName};User={Config.DatabaseUser};" +
                                  $"Password={Config.DatabasePassword};SslMode=None;";

    private static readonly PluginCapability<IMenuApi> MenuCapability = new("menu:nfcore");
    private IMenuApi? _menuApi;

    // Reflection handles into WeaponPaints — used to refresh a player's loadout
    // directly (bypass !wp chat path which doesn't reliably trigger from another plugin)
    private object? _wpInstance;
    private System.Reflection.MethodInfo? _wpRefreshWeapons;
    private object? _wpWeaponSync;
    private System.Reflection.MethodInfo? _wpGetPlayerData;
    private Type? _wpPlayerInfoType;

    // weapon_name -> list of (paint_id, paint_name)
    private readonly Dictionary<string, List<(int paint, string name)>> _paintsByWeapon = new();
    // gloves: list of (defindex, paint_id, paint_name)
    private readonly List<(int defindex, int paint, string name)> _allGloves = new();

    private static readonly List<(string display, string weaponName, int defindex)> KnifeTypes = new()
    {
        ("Bayonet",          "weapon_bayonet",              500),
        ("Bowie Knife",      "weapon_knife_survival_bowie", 514),
        ("Butterfly Knife",  "weapon_knife_butterfly",      515),
        ("Classic Knife",    "weapon_knife_css",            503),
        ("Falchion Knife",   "weapon_knife_falchion",       512),
        ("Flip Knife",       "weapon_knife_flip",           505),
        ("Gut Knife",        "weapon_knife_gut",            506),
        ("Huntsman Knife",   "weapon_knife_tactical",       509),
        ("Karambit",         "weapon_knife_karambit",       507),
        ("Kukri Knife",      "weapon_knife_kukri",          526),
        ("M9 Bayonet",       "weapon_knife_m9_bayonet",     508),
        ("Navaja Knife",     "weapon_knife_gypsy_jackknife",520),
        ("Nomad Knife",      "weapon_knife_outdoor",        521),
        ("Paracord Knife",   "weapon_knife_cord",           517),
        ("Shadow Daggers",   "weapon_knife_push",           533),
        ("Skeleton Knife",   "weapon_knife_skeleton",       525),
        ("Stiletto Knife",   "weapon_knife_stiletto",       522),
        ("Survival Knife",   "weapon_knife_canis",          518),
        ("Talon Knife",      "weapon_knife_widowmaker",     523),
        ("Ursus Knife",      "weapon_knife_ursus",          519),
    };

    private static readonly Dictionary<int, string> KnifeDefindexToWeaponName =
        KnifeTypes.ToDictionary(k => k.defindex, k => k.weaponName);

    // Curated list of high-value tournament stickers. IDs sourced from
    // WeaponPaints/data/stickers_en.json. Ordered roughly by current market value.
    // Add more here if you want them in !sticker.
    private static readonly List<(int id, string display)> HighValueStickers = new()
    {
        // Katowice 2014 Holos - Top tier ($70k+)
        ( 74, "Reason Gaming (Holo) | Katowice 2014"),    // ~$73k
        ( 76, "Titan (Holo) | Katowice 2014"),            // ~$70k
        ( 60, "iBUYPOWER (Holo) | Katowice 2014"),        // ~$62k
        // Boston 2018 Golds - Tournament champion player stickers
        (2863, "Happy (Gold) | Boston 2018"),             // ~$26k
        // Katowice 2014 Holos - High tier ($10-25k)
        (  62, "Team LDLC.com (Holo) | Katowice 2014"),   // ~$23k
        (  80, "Vox Eminor (Holo) | Katowice 2014"),      // ~$23k
        (  53, "Team Dignitas (Holo) | Katowice 2014"),   // ~$23k
        (2911, "bondik (Gold) | Boston 2018"),            // ~$18k
        (  70, "Natus Vincere (Holo) | Katowice 2014"),   // ~$11k
        // Katowice 2014 Holos - Mid tier ($5-10k)
        (  58, "HellRaisers (Holo) | Katowice 2014"),     // ~$8k
        (  72, "Ninjas in Pyjamas (Holo) | Katowice 2014"), // ~$7k
        (  73, "Reason Gaming | Katowice 2014"),          // paper, ~$7k
        (2914, "captainMo (Gold) | Boston 2018"),         // ~$6k
        (  59, "iBUYPOWER | Katowice 2014"),              // paper, ~$5k
        // Katowice 2014 Holos - Other notable
        (  49, "3DMAX (Holo) | Katowice 2014"),
        (  51, "compLexity Gaming (Holo) | Katowice 2014"),
        (  64, "LGB eSports (Holo) | Katowice 2014"),
        (  66, "mousesports (Holo) | Katowice 2014"),
        // Foils and special
        (  37, "Crown (Foil)"),
        ( 102, "King on the Field"),
        ( 103, "Howling Dawn"),
    };

    private static readonly Dictionary<int, string> DopplerPhaseTag = new()
    {
        { 415, "Ruby" }, { 416, "Sapphire" }, { 417, "Black Pearl" },
        { 418, "Phase 1" }, { 419, "Phase 2" }, { 420, "Phase 3" }, { 421, "Phase 4" },
        // Butterfly Knife-specific Doppler paints (user-verified in-game):
        { 617, "Black Pearl (BFK)" },
        { 618, "Phase 2 (BFK)" },  // pink/galaxy, sometimes mistaken for Ruby
        { 619, "Sapphire (BFK)" },
        { 852, "Phase 1 (Talon)" }, { 853, "Phase 2 (Talon)" }, { 854, "Phase 3 (Talon)" }, { 855, "Phase 4 (Talon)" },
        { 568, "Emerald" }, { 569, "GD Phase 1" }, { 570, "GD Phase 2" }, { 571, "GD Phase 3" }, { 572, "GD Phase 4" },
    };

    // ============================================================
    // Plugin lifecycle
    // ============================================================
    public override void Load(bool hotReload)
    {
        LoadSkinData();
        LoadGloveData();
        AddCommandListener("say",      OnPlayerSay, HookMode.Pre);
        AddCommandListener("say_team", OnPlayerSay, HookMode.Pre);
        Console.WriteLine($"[SeedCommand 4.0] loaded — {_paintsByWeapon.Count} weapon types, {_allGloves.Count} glove skins.");
    }

    public override void OnAllPluginsLoaded(bool hotReload)
    {
        _menuApi = MenuCapability.Get();
        Console.WriteLine(_menuApi == null
            ? "[SeedCommand] WARNING: MenuManager (menu:nfcore) not loaded."
            : "[SeedCommand] MenuManager acquired.");
        TryHookWeaponPaints();
    }

    // Find WeaponPaints plugin via reflection and cache the method handles we need.
    // Lets us refresh a player's loadout without going through the !wp chat trigger
    // (which doesn't reliably fire when injected via ExecuteClientCommand).
    private void TryHookWeaponPaints()
    {
        try
        {
            var wpAsm = AppDomain.CurrentDomain.GetAssemblies()
                .FirstOrDefault(a => a.GetName().Name == "WeaponPaints");
            if (wpAsm == null) { Console.WriteLine("[SeedCommand] WeaponPaints assembly not found."); return; }

            var wpType = wpAsm.GetTypes().FirstOrDefault(t => t.Name == "WeaponPaints" && typeof(BasePlugin).IsAssignableFrom(t));
            if (wpType == null) { Console.WriteLine("[SeedCommand] WeaponPaints class not found."); return; }

            // Static Instance property
            var instanceProp = wpType.GetProperty("Instance",
                System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
            _wpInstance = instanceProp?.GetValue(null);
            if (_wpInstance == null)
            {
                var instanceField = wpType.GetField("Instance",
                    System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                _wpInstance = instanceField?.GetValue(null);
            }
            if (_wpInstance == null) { Console.WriteLine("[SeedCommand] WeaponPaints.Instance not accessible."); return; }

            _wpRefreshWeapons = wpType.GetMethod("RefreshWeapons",
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);

            // WeaponSync field on the WeaponPaints instance
            var wsField = wpType.GetField("WeaponSync",
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);
            _wpWeaponSync = wsField?.GetValue(_wpInstance);
            if (_wpWeaponSync != null)
            {
                _wpGetPlayerData = _wpWeaponSync.GetType().GetMethod("GetPlayerData");
            }

            _wpPlayerInfoType = wpAsm.GetType("WeaponPaints.PlayerInfo");

            Console.WriteLine($"[SeedCommand] WP refs: instance={_wpInstance != null}, RefreshWeapons={_wpRefreshWeapons != null}, GetPlayerData={_wpGetPlayerData != null}, PlayerInfo={_wpPlayerInfoType != null}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[SeedCommand] WP reflection error: {ex.Message}");
        }
    }

    // Refresh a player's loadout in WeaponPaints WITHOUT relying on the !wp chat trigger.
    // Calls WP.WeaponSync.GetPlayerData() (reloads cache from DB) then WP.RefreshWeapons() (drops + re-gives).
    private void TriggerWpRefresh(CCSPlayerController player)
    {
        if (_wpInstance == null || _wpRefreshWeapons == null) return;
        try
        {
            // Refresh DB cache (async fire-and-forget)
            if (_wpGetPlayerData != null && _wpPlayerInfoType != null && _wpWeaponSync != null)
            {
                var pi = Activator.CreateInstance(_wpPlayerInfoType);
                if (pi != null)
                {
                    SetIfExists(pi, "UserId",    player.UserId);
                    SetIfExists(pi, "Slot",      player.Slot);
                    SetIfExists(pi, "Index",     (int)player.Index);
                    SetIfExists(pi, "SteamId",   player.SteamID.ToString());
                    SetIfExists(pi, "Name",      player.PlayerName);
                    SetIfExists(pi, "IpAddress", player.IpAddress?.Split(':')[0] ?? "");
                    _wpGetPlayerData.Invoke(_wpWeaponSync, new object[] { pi });
                }
            }
            // Re-apply weapons (drops + re-spawns with fresh cached paints)
            _wpRefreshWeapons.Invoke(_wpInstance, new object[] { player });
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[SeedCommand] TriggerWpRefresh error: {ex.Message}");
        }
    }

    private static void SetIfExists(object obj, string propName, object? value)
    {
        var prop = obj.GetType().GetProperty(propName);
        if (prop != null && prop.CanWrite) { try { prop.SetValue(obj, value); } catch { } }
        var field = obj.GetType().GetField(propName);
        if (field != null) { try { field.SetValue(obj, value); } catch { } }
    }

    public override void Unload(bool hotReload)
    {
        RemoveCommandListener("say",      OnPlayerSay, HookMode.Pre);
        RemoveCommandListener("say_team", OnPlayerSay, HookMode.Pre);
    }

    private string ResolveJsonPath(string configValue, string fileName)
    {
        if (!string.IsNullOrEmpty(configValue) && File.Exists(configValue))
            return configValue;

        // CS# BasePlugin.ModulePath returns the plugin's DLL full path (reliable across loaders)
        string? dllPath = null;
        try { dllPath = ModulePath; } catch { }

        var dllDir = !string.IsNullOrEmpty(dllPath) ? Path.GetDirectoryName(dllPath) ?? "" : "";
        // Sibling plugin folder pattern: plugins/SeedCommand/ -> plugins/WeaponPaints/data/<file>
        if (!string.IsNullOrEmpty(dllDir))
        {
            var candidate = Path.GetFullPath(Path.Combine(dllDir, "..", "WeaponPaints", "data", fileName));
            if (File.Exists(candidate)) return candidate;
        }

        // Final fallback: relative to game's working directory
        var cwd = Directory.GetCurrentDirectory();
        var fallback = Path.GetFullPath(Path.Combine(cwd, "..", "..", "csgo", "addons", "counterstrikesharp", "plugins", "WeaponPaints", "data", fileName));
        return fallback;
    }

    private string ResolveSkinsJsonPath()  => ResolveJsonPath(Config.SkinsJsonPath,  "skins_en.json");
    private string ResolveGlovesJsonPath() => ResolveJsonPath(Config.GlovesJsonPath, "gloves_en.json");

    private void LoadSkinData()
    {
        var path = ResolveSkinsJsonPath();
        try
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            foreach (var entry in doc.RootElement.EnumerateArray())
            {
                if (!entry.TryGetProperty("weapon_name", out var wName)) continue;
                if (!entry.TryGetProperty("paint",       out var paintEl)) continue;
                if (!entry.TryGetProperty("paint_name",  out var nameEl)) continue;
                var weapon = wName.GetString() ?? ""; if (string.IsNullOrEmpty(weapon)) continue;
                int paintId;
                if (paintEl.ValueKind == JsonValueKind.String)
                {
                    if (!int.TryParse(paintEl.GetString(), out paintId)) continue;
                }
                else if (paintEl.ValueKind == JsonValueKind.Number) paintId = paintEl.GetInt32();
                else continue;
                var paintName = nameEl.GetString() ?? "?";
                if (!_paintsByWeapon.TryGetValue(weapon, out var list))
                {
                    list = new List<(int, string)>();
                    _paintsByWeapon[weapon] = list;
                }
                list.Add((paintId, paintName));
            }
            foreach (var key in _paintsByWeapon.Keys.ToList())
                _paintsByWeapon[key] = _paintsByWeapon[key].OrderBy(x => x.name).ToList();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[SeedCommand] FAILED loading skins from {path}: {ex.Message}");
        }
    }

    private void LoadGloveData()
    {
        var path = ResolveGlovesJsonPath();
        try
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            foreach (var entry in doc.RootElement.EnumerateArray())
            {
                if (!entry.TryGetProperty("weapon_defindex", out var defEl)) continue;
                if (!entry.TryGetProperty("paint",           out var paintEl)) continue;
                if (!entry.TryGetProperty("paint_name",      out var nameEl)) continue;
                int defindex = defEl.ValueKind == JsonValueKind.Number ? defEl.GetInt32() : 0;
                int paintId;
                if (paintEl.ValueKind == JsonValueKind.String)
                {
                    if (!int.TryParse(paintEl.GetString(), out paintId)) continue;
                }
                else if (paintEl.ValueKind == JsonValueKind.Number) paintId = paintEl.GetInt32();
                else continue;
                var paintName = nameEl.GetString() ?? "?";
                _allGloves.Add((defindex, paintId, paintName));
            }
            _allGloves.Sort((a, b) => string.Compare(a.name, b.name, StringComparison.OrdinalIgnoreCase));
        }
        catch (Exception ex)
        {
            Console.WriteLine($"[SeedCommand] FAILED loading gloves from {path}: {ex.Message}");
        }
    }

    // ============================================================
    // Chat router — intercepts !k, !ws, !gloves before WeaponPaints
    // ============================================================
    private HookResult OnPlayerSay(CCSPlayerController? player, CommandInfo info)
    {
        if (player == null || !player.IsValid || player.IsBot) return HookResult.Continue;
        if (info.ArgCount < 2) return HookResult.Continue;
        string text = info.GetArg(1).Trim().ToLowerInvariant();
        if (string.IsNullOrEmpty(text)) return HookResult.Continue;
        string firstWord = text.Split(' ', '\t')[0];
        int slot = player.Slot;

        switch (firstWord)
        {
            case "!k":
            case "!knife":
                Server.NextFrame(() => OpenKnifeTypeMenu(slot));
                return HookResult.Stop;
            case "!ws":
                Server.NextFrame(() => OpenHeldWeaponSkinMenu(slot));
                return HookResult.Stop;
            case "!gloves":
                Server.NextFrame(() => OpenGlovesMenu(slot));
                return HookResult.Stop;
            case "!sticker":
            case "!stickers":
                Server.NextFrame(() => OpenStickerMenu(slot));
                return HookResult.Stop;
        }

        return HookResult.Continue;
    }

    // ============================================================
    // !k → knife type menu → skin menu → apply
    // ============================================================
    private void OpenKnifeTypeMenu(int slot)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        var menu = CreateMenu("Pick a knife");
        if (menu == null) { p.PrintToChat(" \x07[Seed]\x01 Menu creation failed."); return; }
        dynamic menuDyn = menu;

        foreach (var (display, weaponName, defindex) in KnifeTypes)
        {
            string capW = weaponName; int capD = defindex; string capDisplay = display;
            Action<CCSPlayerController, object> handler = (caller, opt) =>
            {
                if (caller == null || !caller.IsValid) return;
                OnKnifeTypePicked(caller.Slot, capW, capD, capDisplay);
            };
            menuDyn.AddMenuOption(display, handler);
        }
        AppendCreditOption(menuDyn);
        menuDyn.Open(p);
    }

    private void OnKnifeTypePicked(int slot, string weaponName, int defindex, string display)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        string steamId = p.SteamID.ToString();
        int team = p.TeamNum;

        Task.Run(async () =>
        {
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = @"INSERT INTO wp_player_knife (steamid, weapon_team, knife)
                                    VALUES (@sid, @team, @knife)
                                    ON DUPLICATE KEY UPDATE knife = @knife";
                cmd.Parameters.AddWithValue("@sid",   steamId);
                cmd.Parameters.AddWithValue("@team",  team);
                cmd.Parameters.AddWithValue("@knife", weaponName);
                await cmd.ExecuteNonQueryAsync();
            }
            catch { }

            Server.NextFrame(() =>
            {
                var pp = Utilities.GetPlayerFromSlot(slot);
                if (pp == null || !pp.IsValid) return;
                pp.PrintToChat($" \x06[Seed]\x01 Knife: \x06{display}\x01 — pick a skin:");
                ShowSkinMenuForWeapon(slot, weaponName, defindex, display);
            });
        });
    }

    // ============================================================
    // !ws → skin menu for held weapon → apply
    // ============================================================
    private void OpenHeldWeaponSkinMenu(int slot)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        var pawn = p.PlayerPawn.Value;
        var active = pawn?.WeaponServices?.ActiveWeapon.Value;
        if (active == null || !active.IsValid) { p.PrintToChat(" \x07[Seed]\x01 Hold a weapon first."); return; }

        int defindex = active.AttributeManager.Item.ItemDefinitionIndex;
        string weaponName = active.DesignerName;
        // strip "_weapon_" prefix variants — DesignerName is e.g. "weapon_ak47"
        string display = weaponName.Replace("weapon_", "").Replace("knife_", "Knife ").Replace("_", " ");

        ShowSkinMenuForWeapon(slot, weaponName, defindex, display);
    }

    private void ShowSkinMenuForWeapon(int slot, string weaponName, int defindex, string displayName)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        if (!_paintsByWeapon.TryGetValue(weaponName, out var paints) || paints.Count == 0)
        {
            p.PrintToChat($" \x07[Seed]\x01 No paints found for {weaponName}");
            return;
        }
        var menu = CreateMenu($"Skins for {displayName}");
        if (menu == null) return;
        dynamic menuDyn = menu;

        foreach (var (paintId, paintName) in paints)
        {
            string fullName = DecoratePaintName(paintId, paintName);
            string label = fullName;
            int pipeIdx = label.LastIndexOf('|');
            if (pipeIdx > 0 && pipeIdx + 1 < label.Length) label = label.Substring(pipeIdx + 1).Trim();
            if (label.Contains("Doppler")) label = $"{label} [{paintId}]";

            int capPaint = paintId; string capName = fullName; string capWeapon = weaponName; int capDef = defindex;
            Action<CCSPlayerController, object> h = (c, o) =>
            {
                if (c == null || !c.IsValid) return;
                ApplySkin(c.Slot, capDef, capPaint, capName, capWeapon);
            };
            menuDyn.AddMenuOption(label, h);
        }
        AppendCreditOption(menuDyn);
        menuDyn.Open(p);
    }

    private static string DecoratePaintName(int paintId, string paintName)
        => DopplerPhaseTag.TryGetValue(paintId, out var tag) ? $"{paintName} ({tag})" : paintName;

    // ============================================================
    // !gloves → flat glove menu → apply
    // ============================================================
    private void OpenGlovesMenu(int slot)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        if (_allGloves.Count == 0) { p.PrintToChat(" \x07[Seed]\x01 No glove data loaded."); return; }
        var menu = CreateMenu("Pick gloves");
        if (menu == null) return;
        dynamic menuDyn = menu;

        foreach (var (defindex, paint, name) in _allGloves)
        {
            string label = name;
            int pipeIdx = label.LastIndexOf('|');
            if (pipeIdx > 0 && pipeIdx + 1 < label.Length) label = label.Substring(pipeIdx + 1).Trim();
            int capDef = defindex; int capPaint = paint; string capName = name;
            Action<CCSPlayerController, object> h = (c, o) =>
            {
                if (c == null || !c.IsValid) return;
                ApplyGloves(c.Slot, capDef, capPaint, capName);
            };
            menuDyn.AddMenuOption(label, h);
        }
        AppendCreditOption(menuDyn);
        menuDyn.Open(p);
    }

    private void ApplyGloves(int slot, int defindex, int paintId, string paintName)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        string steamId = p.SteamID.ToString();
        int team = p.TeamNum;

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                // wp_player_gloves selects which glove TYPE is equipped
                await using var c1 = conn.CreateCommand();
                c1.CommandText = @"INSERT INTO wp_player_gloves (steamid, weapon_team, weapon_defindex)
                                   VALUES (@sid, @team, @def)
                                   ON DUPLICATE KEY UPDATE weapon_defindex = @def";
                c1.Parameters.AddWithValue("@sid", steamId);
                c1.Parameters.AddWithValue("@team", team);
                c1.Parameters.AddWithValue("@def", defindex);
                await c1.ExecuteNonQueryAsync();

                // wp_player_skins holds the paint for that glove defindex
                await using var c2 = conn.CreateCommand();
                c2.CommandText = @"INSERT INTO wp_player_skins (steamid, weapon_team, weapon_defindex, weapon_paint_id, weapon_wear, weapon_seed)
                                   VALUES (@sid, @team, @def, @paint, 0.000001, 0)
                                   ON DUPLICATE KEY UPDATE weapon_paint_id = @paint";
                c2.Parameters.AddWithValue("@sid", steamId);
                c2.Parameters.AddWithValue("@team", team);
                c2.Parameters.AddWithValue("@def", defindex);
                c2.Parameters.AddWithValue("@paint", paintId);
                await c2.ExecuteNonQueryAsync();
                reply = $" \x06[Seed]\x01 Gloves: \x06{paintName}\x01. Next round for visual change.";
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var pp = Utilities.GetPlayerFromSlot(slot);
                if (pp != null && pp.IsValid) { pp.PrintToChat(reply); TriggerWpRefresh(pp); }
            });
        });
    }

    // ============================================================
    // !sticker → menu of high-value stickers → slot picker → apply
    // ============================================================
    private void OpenStickerMenu(int slot)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        var (active, _) = GetHeldWeapon(p);
        if (active == null) { p.PrintToChat(" \x07[Seed]\x01 Hold a weapon first."); return; }

        int defindex = active.AttributeManager.Item.ItemDefinitionIndex;
        string weaponClassname = active.DesignerName;

        var menu = CreateMenu("Pick a sticker");
        if (menu == null) return;
        dynamic menuDyn = menu;

        foreach (var (id, display) in HighValueStickers)
        {
            int capId = id; string capDisplay = display;
            int capDef = defindex; string capCls = weaponClassname;
            Action<CCSPlayerController, object> h = (c, o) =>
            {
                if (c == null || !c.IsValid) return;
                OpenStickerSlotMenu(c.Slot, capDef, capCls, capId, capDisplay);
            };
            menuDyn.AddMenuOption(display, h);
        }
        AppendCreditOption(menuDyn);
        menuDyn.Open(p);
    }

    private void OpenStickerSlotMenu(int slot, int defindex, string weaponClassname, int stickerId, string stickerName)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        var menu = CreateMenu($"{stickerName} — pick a slot");
        if (menu == null) return;
        dynamic menuDyn = menu;

        for (int i = 0; i < 5; i++)
        {
            int capSlotIdx = i;
            int capDef = defindex; string capCls = weaponClassname; int capStickerId = stickerId; string capStickerName = stickerName;
            Action<CCSPlayerController, object> h = (c, o) =>
            {
                if (c == null || !c.IsValid) return;
                ApplySticker(c.Slot, capDef, capCls, capSlotIdx, capStickerId, capStickerName);
            };
            menuDyn.AddMenuOption($"Slot {capSlotIdx + 1}", h);
        }
        // Also offer "All 5 slots" as a convenience
        int allDef = defindex; string allCls = weaponClassname; int allId = stickerId; string allName = stickerName;
        Action<CCSPlayerController, object> applyAll = (c, o) =>
        {
            if (c == null || !c.IsValid) return;
            for (int i = 0; i < 5; i++) ApplySticker(c.Slot, allDef, allCls, i, allId, allName, suppressRefresh: i < 4);
        };
        menuDyn.AddMenuOption("ALL 5 slots", applyAll);
        menuDyn.Open(p);
    }

    private void ApplySticker(int slot, int defindex, string weaponClassname, int stickerSlot, int stickerId, string stickerName, bool suppressRefresh = false)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        string steamId = p.SteamID.ToString();
        int team = p.TeamNum;
        string column = $"weapon_sticker_{stickerSlot}";
        // WP sticker DB format: id;schema;OffsetX;OffsetY;Wear;Scale;Rotation
        string stickerData = $"{stickerId};0;0;0;0;1;0";

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                // Column name is hardcoded (whitelist via stickerSlot 0-4 only) so SQL injection safe
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = $@"
                    INSERT INTO wp_player_skins (steamid, weapon_team, weapon_defindex, weapon_paint_id, weapon_wear, weapon_seed, {column})
                    VALUES (@sid, @team, @def, 0, 0.000001, 0, @data)
                    ON DUPLICATE KEY UPDATE {column} = @data";
                cmd.Parameters.AddWithValue("@sid", steamId);
                cmd.Parameters.AddWithValue("@team", team);
                cmd.Parameters.AddWithValue("@def", defindex);
                cmd.Parameters.AddWithValue("@data", stickerData);
                await cmd.ExecuteNonQueryAsync();
                reply = $" \x06[Seed]\x01 Sticker slot {stickerSlot + 1}: \x06{stickerName}\x01 applied.";
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var pp = Utilities.GetPlayerFromSlot(slot);
                if (pp == null || !pp.IsValid) return;
                pp.PrintToChat(reply);
                if (!suppressRefresh) TriggerWpRefresh(pp);
            });
        });
    }

    // ============================================================
    // Apply a skin to a non-glove weapon, then refresh
    // ============================================================
    private void ApplySkin(int slot, int defindex, int paintId, string paintName, string weaponClassname)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;
        string steamId = p.SteamID.ToString();
        int team = p.TeamNum;

        Task.Run(async () =>
        {
            string reply; int seed = 0;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = @"INSERT INTO wp_player_skins (steamid, weapon_team, weapon_defindex, weapon_paint_id, weapon_wear, weapon_seed)
                                    VALUES (@sid, @team, @def, @paint, 0.000001, 0)
                                    ON DUPLICATE KEY UPDATE weapon_paint_id = @paint";
                cmd.Parameters.AddWithValue("@sid",   steamId);
                cmd.Parameters.AddWithValue("@team",  team);
                cmd.Parameters.AddWithValue("@def",   defindex);
                cmd.Parameters.AddWithValue("@paint", paintId);
                await cmd.ExecuteNonQueryAsync();

                await using var read = conn.CreateCommand();
                read.CommandText = "SELECT weapon_seed FROM wp_player_skins WHERE steamid=@sid AND weapon_team=@team AND weapon_defindex=@def";
                read.Parameters.AddWithValue("@sid", steamId); read.Parameters.AddWithValue("@team", team); read.Parameters.AddWithValue("@def", defindex);
                seed = Convert.ToInt32(await read.ExecuteScalarAsync() ?? 0);

                reply = $" \x06[Seed]\x01 \x06{paintName}\x01 (paint {paintId}, seed {seed}, FN).";
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var pp = Utilities.GetPlayerFromSlot(slot);
                if (pp == null || !pp.IsValid) return;
                pp.PrintToChat(reply);
                // Directly invoke WeaponPaints' refresh via reflection - bypasses the chat trigger
                TriggerWpRefresh(pp);
            });
        });
    }

    private void ForceWeaponRefresh(int slot, string weaponClassname)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return;

        // Strategy 1: Full respawn — most reliable, WeaponPaints reloads loadout from DB on spawn.
        // Use this for practice/bot servers where position loss is acceptable.
        if (Config.ForceRespawnOnSkinChange)
        {
            try { p.Respawn(); return; } catch { /* fall through to drop+give */ }
        }

        // Strategy 2: Drop + give (less disruptive but relies on WP's cache being fresh)
        var pawn = p.PlayerPawn.Value;
        if (pawn == null) return;
        try
        {
            var weapons = pawn.WeaponServices?.MyWeapons;
            if (weapons != null)
            {
                foreach (var handle in weapons)
                {
                    var w = handle?.Value;
                    if (w == null || !w.IsValid) continue;
                    if (w.DesignerName == weaponClassname || w.DesignerName.StartsWith(weaponClassname))
                        w.Remove();
                }
            }
            p.ExecuteClientCommandFromServer($"give {weaponClassname}");
        }
        catch { }
    }

    // ============================================================
    // !seed <n> — manual seed override on held weapon
    // ============================================================
    [ConsoleCommand("css_seed", "Set paint seed on held weapon")]
    [CommandHelper(minArgs: 1, usage: "<seed_number>", whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnSeed(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        if (!int.TryParse(command.GetArg(1), out int seed) || seed < 0 || seed > 1000000)
        { command.ReplyToCommand(" \x07[Seed]\x01 Usage: !seed <0 - 1000000>"); return; }
        ApplyHeldWeaponField(player, "weapon_seed", seed, $"seed=\x06{seed}\x01");
    }

    // ============================================================
    // !bestseed — apply best community-known seed for held weapon's current paint
    // ============================================================
    [ConsoleCommand("css_bestseed", "Apply the best community seed for the held weapon's current paint")]
    [CommandHelper(whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnBestSeed(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        var (active, _) = GetHeldWeapon(player);
        if (active == null) { command.ReplyToCommand(" \x07[Seed]\x01 Hold a weapon first."); return; }
        int defindex = active.AttributeManager.Item.ItemDefinitionIndex;
        int team = player.TeamNum; string steamId = player.SteamID.ToString(); int slot = player.Slot;

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = @"
                    UPDATE wp_player_skins s
                    JOIN best_seeds bs ON bs.weapon_defindex = s.weapon_defindex AND bs.weapon_paint_id = s.weapon_paint_id
                    SET s.weapon_seed = bs.best_seed
                    WHERE s.steamid = @sid AND s.weapon_team = @team AND s.weapon_defindex = @def";
                cmd.Parameters.AddWithValue("@sid", steamId);
                cmd.Parameters.AddWithValue("@team", team);
                cmd.Parameters.AddWithValue("@def", defindex);
                int rows = await cmd.ExecuteNonQueryAsync();
                reply = rows > 0
                    ? " \x06[Seed]\x01 Best seed applied. Refreshing..."
                    : " \x07[Seed]\x01 No best-seed entry for this paint (skin uses default seed).";
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var p = Utilities.GetPlayerFromSlot(slot);
                if (p != null && p.IsValid)
                {
                    p.PrintToChat(reply);
                    TriggerWpRefresh(p);
                }
            });
        });
    }

    // ============================================================
    // !wear <float> — set wear/float of held weapon
    // ============================================================
    [ConsoleCommand("css_wear", "Set wear (float) of held weapon. 0.000001=Factory New, 0.5=Battle-Scarred")]
    [ConsoleCommand("css_float", "Alias of css_wear")]
    [CommandHelper(minArgs: 1, usage: "<float 0.0-1.0>", whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnWear(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        if (!float.TryParse(command.GetArg(1), NumberStyles.Float, CultureInfo.InvariantCulture, out float wear) || wear < 0f || wear > 1f)
        { command.ReplyToCommand(" \x07[Seed]\x01 Usage: !wear <0.0 - 1.0>"); return; }
        // CS2's actual minimum wear is 0.000001 — clamp upward so the row is accepted
        if (wear <= 0f) wear = 0.000001f;
        ApplyHeldWeaponField(player, "weapon_wear", wear, $"wear=\x06{wear:F4}\x01 ({WearTier(wear)})");
    }

    [ConsoleCommand("css_fn", "Shortcut for !wear 0.000001 (Factory New minimum)")]
    [CommandHelper(whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnFn(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        ApplyHeldWeaponField(player, "weapon_wear", 0.000001f, "wear=\x06FN\x01");
    }

    // ============================================================
    // !glovebestseed — apply the best community seed for equipped gloves' current paint
    // ============================================================
    [ConsoleCommand("css_glovebestseed", "Apply the best community seed for equipped gloves' current paint")]
    [CommandHelper(whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnGloveBestSeed(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        int team = player.TeamNum;
        string steamId = player.SteamID.ToString();
        int slot = player.Slot;

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();

                // Find equipped glove defindex
                await using var lookup = conn.CreateCommand();
                lookup.CommandText = "SELECT weapon_defindex FROM wp_player_gloves WHERE steamid=@sid AND weapon_team=@team";
                lookup.Parameters.AddWithValue("@sid", steamId);
                lookup.Parameters.AddWithValue("@team", team);
                var defObj = await lookup.ExecuteScalarAsync();

                if (defObj == null)
                {
                    reply = " \x07[Seed]\x01 No gloves equipped. Pick gloves via !gloves first.";
                }
                else
                {
                    int gloveDef = Convert.ToInt32(defObj);
                    // Join best_seeds against the player's current glove paint and apply
                    await using var upd = conn.CreateCommand();
                    upd.CommandText = @"
                        UPDATE wp_player_skins s
                        JOIN best_seeds bs ON bs.weapon_defindex = s.weapon_defindex AND bs.weapon_paint_id = s.weapon_paint_id
                        SET s.weapon_seed = bs.best_seed
                        WHERE s.steamid = @sid AND s.weapon_team = @team AND s.weapon_defindex = @def";
                    upd.Parameters.AddWithValue("@sid", steamId);
                    upd.Parameters.AddWithValue("@team", team);
                    upd.Parameters.AddWithValue("@def", gloveDef);
                    int rows = await upd.ExecuteNonQueryAsync();

                    if (rows > 0)
                    {
                        // Read back the actual seed value for the chat message
                        await using var read = conn.CreateCommand();
                        read.CommandText = "SELECT weapon_seed FROM wp_player_skins WHERE steamid=@sid AND weapon_team=@team AND weapon_defindex=@def";
                        read.Parameters.AddWithValue("@sid", steamId);
                        read.Parameters.AddWithValue("@team", team);
                        read.Parameters.AddWithValue("@def", gloveDef);
                        int seed = Convert.ToInt32(await read.ExecuteScalarAsync() ?? 0);
                        reply = $" \x06[Seed]\x01 Best glove seed=\x06{seed}\x01 applied (defindex {gloveDef}). Visible next round.";
                    }
                    else
                    {
                        reply = " \x07[Seed]\x01 No best-seed entry for this glove paint (uniform skin or not yet catalogued).";
                    }
                }
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var p = Utilities.GetPlayerFromSlot(slot);
                if (p != null && p.IsValid)
                {
                    p.PrintToChat(reply);
                    TriggerWpRefresh(p);
                }
            });
        });
    }

    // ============================================================
    // !gloveseed <n> — set seed on currently equipped gloves
    // ============================================================
    [ConsoleCommand("css_gloveseed", "Set paint seed on equipped gloves")]
    [ConsoleCommand("css_glovesseed", "Alias of css_gloveseed")]
    [CommandHelper(minArgs: 1, usage: "<seed_number>", whoCanExecute: CommandUsage.CLIENT_ONLY)]
    public void OnGloveSeed(CCSPlayerController? player, CommandInfo command)
    {
        if (player == null || !player.IsValid || player.IsBot) return;
        if (!int.TryParse(command.GetArg(1), out int seed) || seed < 0 || seed > 1000000)
        { command.ReplyToCommand(" \x07[Seed]\x01 Usage: !gloveseed <0 - 1000000>"); return; }

        int team = player.TeamNum;
        string steamId = player.SteamID.ToString();
        int slot = player.Slot;

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();

                // 1. Look up which glove TYPE is currently equipped
                await using var lookup = conn.CreateCommand();
                lookup.CommandText = "SELECT weapon_defindex FROM wp_player_gloves WHERE steamid=@sid AND weapon_team=@team";
                lookup.Parameters.AddWithValue("@sid", steamId);
                lookup.Parameters.AddWithValue("@team", team);
                var defObj = await lookup.ExecuteScalarAsync();

                if (defObj == null)
                {
                    reply = " \x07[Seed]\x01 No gloves equipped. Pick gloves via !gloves first.";
                }
                else
                {
                    int gloveDef = Convert.ToInt32(defObj);
                    await using var upd = conn.CreateCommand();
                    upd.CommandText = "UPDATE wp_player_skins SET weapon_seed = @seed WHERE steamid=@sid AND weapon_team=@team AND weapon_defindex=@def";
                    upd.Parameters.AddWithValue("@seed", seed);
                    upd.Parameters.AddWithValue("@sid", steamId);
                    upd.Parameters.AddWithValue("@team", team);
                    upd.Parameters.AddWithValue("@def", gloveDef);
                    int rows = await upd.ExecuteNonQueryAsync();
                    reply = rows > 0
                        ? $" \x06[Seed]\x01 Glove seed=\x06{seed}\x01 (defindex {gloveDef}). Refresh: gloves apply visually on next round."
                        : $" \x07[Seed]\x01 No DB row found for glove defindex={gloveDef}. Apply a glove skin via !gloves first.";
                }
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var p = Utilities.GetPlayerFromSlot(slot);
                if (p != null && p.IsValid)
                {
                    p.PrintToChat(reply);
                    TriggerWpRefresh(p);
                }
            });
        });
    }

    // ============================================================
    // StatTrak kill counter — increment on player death
    // ============================================================
    [GameEventHandler]
    public HookResult OnPlayerDeath(EventPlayerDeath @event, GameEventInfo info)
    {
        var killer = @event.Attacker;
        var victim = @event.Userid;
        if (killer == null || !killer.IsValid || killer.IsBot) return HookResult.Continue;
        // Skip suicides and team-kills only when victim == killer
        if (victim != null && killer.SteamID == victim.SteamID) return HookResult.Continue;

        var pawn = killer.PlayerPawn.Value;
        var activeWeapon = pawn?.WeaponServices?.ActiveWeapon.Value;
        if (activeWeapon == null || !activeWeapon.IsValid) return HookResult.Continue;

        ushort defindex = activeWeapon.AttributeManager.Item.ItemDefinitionIndex;
        int team = killer.TeamNum;
        string steamId = killer.SteamID.ToString();

        Task.Run(async () =>
        {
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                // Only increment if this row has StatTrak enabled
                cmd.CommandText = @"
                    UPDATE wp_player_skins
                    SET weapon_stattrak_count = weapon_stattrak_count + 1
                    WHERE steamid = @sid
                      AND weapon_team = @team
                      AND weapon_defindex = @def
                      AND weapon_stattrak = 1";
                cmd.Parameters.AddWithValue("@sid", steamId);
                cmd.Parameters.AddWithValue("@team", team);
                cmd.Parameters.AddWithValue("@def", (int)defindex);
                await cmd.ExecuteNonQueryAsync();
            }
            catch { /* silent — don't spam chat on every kill */ }
        });

        return HookResult.Continue;
    }

    private static string WearTier(float w)
        => w < 0.07f ? "Factory New"
         : w < 0.15f ? "Minimal Wear"
         : w < 0.38f ? "Field-Tested"
         : w < 0.45f ? "Well-Worn"
         : "Battle-Scarred";

    // ============================================================
    // Shared: update a single column on held weapon's row + refresh
    // ============================================================
    private void ApplyHeldWeaponField(CCSPlayerController player, string column, object value, string userVisible)
    {
        var (active, classname) = GetHeldWeapon(player);
        if (active == null) { player.PrintToChat(" \x07[Seed]\x01 Hold a weapon first."); return; }
        ushort defindex = active.AttributeManager.Item.ItemDefinitionIndex;
        int team = player.TeamNum; string steamId = player.SteamID.ToString(); int slot = player.Slot;

        Task.Run(async () =>
        {
            string reply;
            try
            {
                await using var conn = new MySqlConnection(ConnString);
                await conn.OpenAsync();
                await using var cmd = conn.CreateCommand();
                // Column name is hardcoded (whitelist) so SQL injection is impossible
                cmd.CommandText = $"UPDATE wp_player_skins SET {column} = @val WHERE steamid=@sid AND weapon_team=@team AND weapon_defindex=@def";
                cmd.Parameters.AddWithValue("@val", value);
                cmd.Parameters.AddWithValue("@sid", steamId);
                cmd.Parameters.AddWithValue("@team", team);
                cmd.Parameters.AddWithValue("@def", (int)defindex);
                int rows = await cmd.ExecuteNonQueryAsync();
                reply = rows > 0
                    ? $" \x06[Seed]\x01 {userVisible} on defindex=\x06{defindex}\x01."
                    : $" \x07[Seed]\x01 No DB row for team={team} defindex={defindex}.";
            }
            catch (Exception ex) { reply = $" \x07[Seed]\x01 SQL: {ex.Message}"; }

            Server.NextFrame(() =>
            {
                var p = Utilities.GetPlayerFromSlot(slot);
                if (p == null || !p.IsValid) return;
                p.PrintToChat(reply);
                TriggerWpRefresh(p);
            });
        });
    }

    private static (CBasePlayerWeapon?, string) GetHeldWeapon(CCSPlayerController player)
    {
        var pawn = player.PlayerPawn.Value;
        var active = pawn?.WeaponServices?.ActiveWeapon.Value;
        if (active == null || !active.IsValid) return (null, "");
        return (active, active.DesignerName);
    }

    private string GetWeaponClassname(int slot)
    {
        var p = Utilities.GetPlayerFromSlot(slot);
        if (p == null || !p.IsValid) return "";
        var (_, cn) = GetHeldWeapon(p);
        return cn;
    }

    // ============================================================
    // MenuManager helper — reflection bypasses obsolete-as-error
    // ============================================================
    // "by Mavi" credit label rendered in epic-purple, styled as a footer-like divider
    // so it doesn't look selectable. Added as the last menu option since MenuManager
    // doesn't have a native footer/subtitle slot below the W/S/E/R nav hints.
    private const string CreditOption = "── <font color='#A335EE'>by Mavi</font> ──";

    // Appends the credit as a no-op final option on every menu we create.
    private void AppendCreditOption(dynamic menu)
    {
        try
        {
            Action<CCSPlayerController, object> noop = (c, o) => { /* credit label — no action */ };
            menu.AddMenuOption(CreditOption, noop);
        }
        catch { }
    }

    private object? CreateMenu(string title)
    {
        if (_menuApi == null) return null;
        try
        {
            var best = _menuApi.GetType().GetMethods()
                .Where(m => m.Name == "NewMenuForcetype")
                .OrderBy(m => m.GetParameters().Count(pp => !pp.IsOptional))
                .FirstOrDefault();
            if (best == null) return null;
            var parameters = best.GetParameters();
            object?[] args = new object[parameters.Length];
            args[0] = title;
            // ButtonMenu = scrollable center-screen menu with WASD navigation
            args[1] = MenuType.ButtonMenu;
            for (int i = 2; i < parameters.Length; i++)
                args[i] = parameters[i].IsOptional ? Type.Missing : null;
            return best.Invoke(_menuApi, args);
        }
        catch { return null; }
    }
}
